### ISSUE TITLE
Update to Upsilon for the simulator

### ISSUE THREAD

**Issue by gbraad** [k-kuroguro/vscode-numworks#2]
Since Omega is archived it might be better to use he Upsilon fork to based this on as that sees continued improvements.

**Comment by k-kuroguro** [comment]
You are right👍
This extension use simulator resource from https://getomega.dev now.
Instead of that, I want to set Upsilon as a submodule and building it as it is updated.

**Comment by GustavoSchip** [comment]
1+

**Comment by k-kuroguro** [comment]
Updated to Upsilon with commit 97a21672f46cb63756dd3d174d99add42.
