### ISSUE TITLE
Allow loading multiple files

### ISSUE THREAD

**Issue by AFCMS** [k-kuroguro/vscode-numworks#3]
> Note: Now, simulator loads only one opened script. If you import except standard library in it, it won't work well.

This is very annoying IMO.

I often use multiple files.

**Comment by k-kuroguro** [comment]
Right👍
I'm gonna make extension load opening file dependencies or files in opening folder.

**Comment by k-kuroguro** [comment]
Implemented in 1.2.0 (0124fe2818aaac4002f6d07ebe1545e397a95085). Enabling allowMultipleScripts now allows loading sibling scripts of the open script. Note that deep hierarchical structures are not supported.
