### ISSUE TITLE
Unable to open 10k+ files

### ISSUE THREAD

**Issue by immjs** [k-kuroguro/vscode-numworks#4]
Hello,

I am finding myself unable to open my file as soon as it reaches 10k chars. This is a problem since numworks calculators (Or at least the N0110) have a storage capacity beyond that.

Is a fix possible? Thank you

**Comment by GustavoSchip** [comment]
Same here!

**Comment by k-kuroguro** [comment]
Fixed by e5aba06.

**Comment by GustavoSchip** [comment]
Great work @k-kuroguro !
